
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '11':
        pose: mocap_obstacle1/pose
        pose2d: mocap_obstacle1/ground_pose
        child_frame_id: obst1/base_link
        parent_frame_id: map_mocap
    '12':
        pose: mocap_obstacle2/pose
        pose2d: mocap_obstacle2/ground_pose
        child_frame_id: obst2/base_link
        parent_frame_id: map_mocap    
    '13':
        pose: mocap_obstacle3/pose
        pose2d: mocap_obstacle3/ground_pose
        child_frame_id: obst3/base_link
        parent_frame_id: map_mocap
    '14':
        pose: mocap_obstacle4/pose
        pose2d: mocap_obstacle4/ground_pose
        child_frame_id: obst4/base_link
        parent_frame_id: map_mocap
    '15':
        pose: mocap_obstacle5/pose
        pose2d: mocap_obstacle5/ground_pose
        child_frame_id: obst5/base_link
        parent_frame_id: map_mocap
    '10':
       pose: Robot_1/pose
       pose2d: Robot_1/ground_pose
#        child_frame_id: Robot_1/base_link
       child_frame_id: base_link
       parent_frame_id: odom
optitrack_config:
        multicast_address: 224.0.0.1
#        multicast_address: 192.168.209.31
    #multicast_address: 169.254.249
