#
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '1':
        pose: hovergames/pose
        frame_id: odom

optitrack_config:
       multicast_address: 224.0.0.1

remap: 
       frequency: 40
       topic_name: /mavros/vision_pose/pose