#
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '1':
        pose: pedestrian_1/pose
        pose2d: pedestrian_1/ground_pose
        child_frame_id: ped1_link
        parent_frame_id: map
    '2':
        pose: pedestrian_2/pose
        pose2d: pedestrian_2/ground_pose
        child_frame_id: ped2_link
        parent_frame_id: map
    '3':
        pose: Robot/pose
        pose2d: Robot/ground_pose
        child_frame_id: base_link
        parent_frame_id: map
optitrack_config:
        #multicast_address: 192.169.209.203
        #multicast_address: 224.0.0.1
        multicast_address: 192.168.209.81
